site_name: Tim-Wcx
site_url: https://github.tim-wcx.ltd/mkdocs/

theme:
  name: material
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  features:
    - navigation.tabs
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  language: 'zh'

nav:
  - ICPC题解:
      - 组队训练赛（四）: problem/组队训练赛（四）.md
      - 组队训练赛（三）: problem/组队训练赛（三）.md
      - 组队训练赛（二）: problem/组队训练赛（二）.md
      - 组队训练赛（一）: problem/组队训练赛（一）.md
      - 暑假集训系列题解（十五）: problem/暑假集训系列题解（十五）.md
      - 暑假集训系列题解（十四）: problem/暑假集训系列题解（十四）.md
      - 暑假集训系列题解（十三）: problem/暑假集训系列题解（十三）.md
      - 暑假集训系列题解（十二）: problem/暑假集训系列题解（十二）.md
      - 暑假集训系列题解（十一）: problem/暑假集训系列题解（十一）.md
      - 暑假集训系列题解（十）: problem/暑假集训系列题解（十）.md
      - 暑假集训系列题解（九）: problem/暑假集训系列题解（九）.md
      - 暑假集训系列题解（八）: problem/暑假集训系列题解（八）.md
      - 暑假集训系列题解（七）: problem/暑假集训系列题解（七）.md
      - 暑假集训系列题解（六）: problem/暑假集训系列题解（六）.md
      - 暑假集训系列题解（五）: problem/暑假集训系列题解（五）.md
      - 暑假集训系列题解（四）: problem/暑假集训系列题解（四）.md
      - 暑假集训系列题解（三）: problem/暑假集训系列题解（三）.md
      - 暑假集训系列题解（二）: problem/暑假集训系列题解（二）.md
      - 暑假集训题解系列（一）: problem/暑假集训题解系列（一）.md
      - 2021-02-02-2月2日题解: problem/2021-02-02-2月2日题解.md
      - 2021-02-07-2月7日题解: problem/2021-02-07-2月7日题解.md
      - 2021-02-02-2月2日题解: problem/2021-02-02-2月2日题解.md
      - 2021-02-07-2月7日题解: problem/2021-02-07-2月7日题解.md
      - 2021-02-08-2月8日题解: problem/2021-02-08-2月8日题解.md
      - 2021-02-09-2月9日题解: problem/2021-02-09-2月9日题解.md
      - 2021-02-12-安卓课表客户端+服务端注解: problem/2021-02-12-安卓课表客户端+服务端注解.md
      - 2021-02-16-2月16日题解: problem/2021-02-16-2月16日题解.md
      - 2021-02-19-2月19日题解: problem/2021-02-19-2月19日题解.md
      - 2021-02-20-2月20日题解: problem/2021-02-20-2月20日题解.md
      - 2021-02-22-2月22日题解: problem/2021-02-22-2月22日题解.md
      - 2021-02-24-2月24日题解: problem/2021-02-24-2月24日题解.md
      - 2021-02-28-2月28日题解: problem/2021-02-28-2月28日题解.md
      - 2021-03-02-3月2日题解: problem/2021-03-02-3月2日题解.md
      - 2021-03-07-3月7日题解: problem/2021-03-07-3月7日题解.md
      - 2021-03-09-数论: problem/2021-03-09-数论.md
      - 2021-06-05-6月5日题解: problem/2021-06-05-6月5日题解.md
  - ICPC模板:
      - 个人模板: icpc/个人模板.md
      - kuangbin模板: icpc/kuangbin模板.md
  - ICPC题单: question/README.md
  - 课程复习:
      - 数字图像处理: course/数字图像处理.md
      - 现代密码学: course/现代密码学.md
      - 软件工程: course/软件工程.md
      - 计算机图形学: course/计算机图形学.md
      - 计算机操作系统: course/计算机操作系统.md
  - csdn导出:
      - 2020-08-01: csdn/2020-08-01.md
      - 2020-08-02线段树: csdn/2020-08-02线段树.md
      - 2020-08-03: csdn/2020-08-03.md
      - 2020-08-04: csdn/2020-08-04.md
      - 2020-08-05: csdn/2020-08-05.md
      - 2020-08-06线段树: csdn/2020-08-06线段树.md
      - 2020-08-07: csdn/2020-08-07.md
      - 2020-08-08: csdn/2020-08-08.md
      - 2020-08-09: csdn/2020-08-09.md
      - 2020-08-10: csdn/2020-08-10.md
      - 2020-08-11: csdn/2020-08-11.md
      - 2020-08-12欧拉函数: csdn/2020-08-12欧拉函数.md
      - 2020-08-13: csdn/2020-08-13.md
      - 2020-08-14: csdn/2020-08-14.md
      - 2020-08-16树形DP+等差数列前缀和: csdn/2020-08-16树形DP+等差数列前缀和.md
      - 2020-08-17: csdn/2020-08-17.md
      - 2020-08-18: csdn/2020-08-18.md
      - 2020-08-19: csdn/2020-08-19.md
      - 2020-08-20: csdn/2020-08-20.md
      - 2020-08-21: csdn/2020-08-21.md
      - 2020-09-05划分树求某一区间的中位数: csdn/2020-09-05划分树求某一区间的中位数.md
      - 2020-09-07: csdn/2020-09-07.md
      - 2020-09-08二分+最小生成树: csdn/2020-09-08二分+最小生成树.md
      - 2020-09-08数位DP+二分: csdn/2020-09-08数位DP+二分.md
      - 2020-09-09数位DP: csdn/2020-09-09数位DP.md
      - 2020-09-11树状数组求最大值: csdn/2020-09-11树状数组求最大值.md
      - 2020-09-12字符串哈希: csdn/2020-09-12字符串哈希.md
      - 2020-09-12: csdn/2020-09-12.md
      - 2020-09-21凸包算法: csdn/2020-09-21凸包算法.md
      - 2020-09-23树状数组: csdn/2020-09-23树状数组.md
      - 2020-09-26最小费用最大流问题: csdn/2020-09-26最小费用最大流问题.md
      - 2020-10-04线段树+扫描线: csdn/2020-10-04线段树+扫描线.md
      - 2020-10-05: csdn/2020-10-05.md
      - 2020-10-07并查集+启发式合并: csdn/2020-10-07并查集+启发式合并.md
      - 2020-10-15dsuontree: csdn/2020-10-15dsuontree.md
      - 2020-11-23: csdn/2020-11-23.md
      - 2020-12-02: csdn/2020-12-02.md
      - 2020-7-31: csdn/2020-7-31.md
      - 2021-02-02: csdn/2021-02-02.md
      - 2021-02-24: csdn/2021-02-24.md
      - Beyondcompare430天试用过期: csdn/Beyond_compare4_30天试用过期.md
      - GitHub博客: csdn/GitHub博客.md
      - 二分+二分查找模板: csdn/二分+二分查找模板.md
      - 异或求和式: csdn/异或求和式.md
      - 求组合数的方法: csdn/求组合数的方法.md
      - 求逆序对: csdn/求逆序对.md
      - 简介扩展欧几里德定理: csdn/简介扩展欧几里德定理.md
      - 链表: csdn/链表.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'