name: mkdocs

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    #引用外部Action,拉取代码仓库到虚拟机工作目录
    - name : pull docsify
      run: |
        mkdir docs
        dir
        cd docs
        git init
        git pull https://github.com/WCX1024979076/docsify.git
        dir
        
    
    - name: pull mkdocs
      run: |
        mkdir site
        dir
        cd site
        git init
        git pull https://github.com/WCX1024979076/mkdocs.git
        dir

    # 安装 mkdocs
    - name: show dir
      run: |
        dir
    
    # 搭建环境 pyhton
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    # 安装 mkdocs
    - name: Install mkdocs and mkdocs-material
      run: |
        python -m pip install mkdocs mkdocs-material

    # 编译安装
    - name : mkdocs bulid
      run: |
        mv ./docs/mkdocs.yml ./mkdocs.yml
        mkdocs build

    #这里是一些额外的操作,通常不需要.这里是为了把编译好的二进制程序push到原始的GitHub仓库
    - name: CommitBinaries
      uses: peaceiris/actions-gh-pages@v3 #和上面一样，这里使用的是他人写好的插件库，作用是发布到其他仓库中或者其他分支上，想要具体了解可以在插件库中搜索
      with:
        deploy_key: ${{ secrets.TOKEN }} # key
        external_repository: WCX1024979076/mkdocs #推送到该仓库中，地址格式为github名称/仓库名
        publish_branch: master #分支名
        publish_dir: site #要推送的内容（打包后的博客文件夹）
    
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        # 注意替换为你的 GitHub 源仓库地址
        source-repo: git@github.com:WCX1024979076/mkdocs.git
        # 注意替换为你的 Gitee 目标仓库地址
        destination-repo: git@gitee.com:WCX1024979076/mkdocs.git


    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        # 注意替换为你的 Gitee 用户名
        gitee-username: 1024979076@qq.com
        # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
        gitee-repo: WCX1024979076/mkdocs
        # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
        branch: master